### PR TITLE
0.17.0

### PR DESCRIPTION
**Pull request by gnestor**
* Upgrade to jupyterlab 0.17.0 (thanks @blink1073 for https://github.com/jupyterlab/jupyterlab_json/pull/19)
* Support `expanded` metadata
* Adopt new mimerender-cookiecutter [workflow](https://github.com/jupyterlab/mimerender-cookiecutter#workflow)

### CODE REVIEW

**Review by blink1073 — APPROVED** [review]

**Comment by blink1073** [comment]
@gnestor, I'm starting to think it makes sense to bump the version of JupyterLab in master before the release, because once we change APIs, the version is no longer correct in semver.  Thoughts?

**Comment by blink1073** [comment]
@jasongrout, you've wrestled with this in ipywidgets, what are your thoughts on using the npm prerelease tags (premajor, preminor, prepatch) in master?

**Comment by jasongrout** [comment]
As an example, we decided to make the prelease versions of jupyter-js-widgets as patch releases on 2.0.x, and publish to npm with `--tag next`. That way a program could easily specify the latest prerelease (e.g., `2.0.*`). The final 2.0 release would either be something like 2.0.40  (similar to Typescript), or in our case, we decided to just bump to 2.1.0. I'm not sure which is better from those.

See also https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420#.cgcduzqkf

**Comment by jasongrout** [comment]
This did break semver of course (every patch release on 2.0.x was probably breaking), but since we published with `--tag next`, we thought the convention would be understandable.

**Comment by blink1073** [comment]
We're about to switch to multi-packages anyway, where the python package version is not tied to the individual packages, but I do like using `@next` for prerelease.  Ick about the `@latest` installing alpha tags though, wow.

**Comment by jasongrout** [comment]
Aside from the next vs latest tags, I think the difference between our approach and the prerelease approach is that having the prereleases as normal patch versions allowed you to do `2.0.*` and get upgraded to the most recent prerelease, whereas (IIRC) true alpha releases are considered incompatible with each other. That's probably more technically correct, but inconvenient when doing development and releasing lots of alpha releases.

**Comment by blink1073** [comment]
I'd argue that that approach is just moving the problem elsewhere, while being technically incorrect.

**Comment by jasongrout** [comment]
I'd say that it's more a symptom of more serious problems elsewhere, namely our conflation of jupyter-js-widgets version number and the version number of the protocol. Basically, we still have a pretty tightly coupled backend and frontend, and doing this helped us work around that for now.

Fixing this and cleanly separating the backend and frontend is one of my goals for widgets 7.0.

**Comment by blink1073** [comment]
There's a reason the Air Force has people whose full time job is configuration management.  ;)

**Comment by jasongrout** [comment]
Given the severity of consequences from Air Force errors, I'm glad!

**Comment by gnestor** [comment]
> @gnestor, I'm starting to think it makes sense to bump the version of JupyterLab in master before the release, because once we change APIs, the version is no longer correct in semver. Thoughts?

My initial thought is if you were to checkout this branch and try to build it, it would fail with `Could not find a version that satisfies the requirement jupyterlab>=0.17.0` (the workaround is to change the jupyterlab version to `0.16.2`). Would what you're proposing fix that?

**Comment by blink1073** [comment]
If we make master `0.17.0`, then this PR would work *until we make another breaking change*.  If we made the policy of bumping a suffix in master whenever there was a suffix change, then master of this repo could track the most recent prerelease.  There's no real great solution for tracking master, but hopefully we can find a workable one.

**Comment by gnestor** [comment]
Sounds like an improvement 👍

**Comment by blink1073** [comment]
Given the subtleties of the `@next` tag, I think bumping the version in master to `-alpha.x` but not releasing might be the best approach.

**Pull request merged**
